package com.neon.upscaler;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.net.Uri;import android.view.*;import android.widget.*;import java.io.*;
public class MainActivity extends Activity {
 static { System.loadLibrary("neon_upscaler"); }
 private native int scaleNative(Bitmap src,Bitmap dst,int mode,float sharp);
 private static final int PICK=1,SAVE=2; private Bitmap source,result; private ImageView before,after; private SeekBar size,sharp; private Spinner filter; private TextView status; private Uri saveUri;
 public void onCreate(Bundle b){super.onCreate(b); LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setPadding(24,20,24,20);root.setBackgroundColor(Color.rgb(13,16,28)); TextView title=new TextView(this);title.setText("NEON AI UPSCALER\nANDROID IMAGE LAB · v0.2");title.setTextColor(Color.WHITE);title.setTextSize(22);root.addView(title);Button pick=new Button(this);pick.setText("Выбрать изображение");root.addView(pick);pick.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK);}); LinearLayout row=new LinearLayout(this);before=new ImageView(this);after=new ImageView(this);before.setScaleType(ImageView.ScaleType.FIT_CENTER);after.setScaleType(ImageView.ScaleType.FIT_CENTER);row.addView(before,new LinearLayout.LayoutParams(0,300,1));row.addView(after,new LinearLayout.LayoutParams(0,300,1));root.addView(row);status=new TextView(this);status.setTextColor(Color.WHITE);root.addView(status);filter=new Spinner(this);filter.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Bilinear","Bicubic"}));root.addView(filter);size=new SeekBar(this);size.setMax(3);size.setProgress(2);root.addView(size);sharp=new SeekBar(this);sharp.setMax(50);sharp.setProgress(15);root.addView(sharp);Button run=new Button(this);run.setText("Масштабировать");root.addView(run);run.setOnClickListener(v->process());Button save=new Button(this);save.setText("Сохранить PNG");root.addView(save);save.setOnClickListener(v->save());setContentView(root); }
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null||d.getData()==null)return;try{if(r==PICK){InputStream in=getContentResolver().openInputStream(d.getData());source=BitmapFactory.decodeStream(in);in.close();before.setImageBitmap(source);process();}else if(r==SAVE&&saveUri!=null){OutputStream o=getContentResolver().openOutputStream(saveUri);result.compress(Bitmap.CompressFormat.PNG,100,o);o.close();Toast.makeText(this,"Сохранено",0).show();}}catch(Exception e){Toast.makeText(this,e.getMessage(),1).show();}}
 private void process(){if(source==null)return;int[] sizes={480,720,1080,1440};int max=sizes[size.getProgress()];float ratio=Math.min(1f,(float)max/Math.max(source.getWidth(),source.getHeight()));int w=Math.max(1,Math.round(source.getWidth()*ratio)),h=Math.max(1,Math.round(source.getHeight()*ratio));result=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);long t=System.nanoTime();int rc=scaleNative(source,result,filter.getSelectedItemPosition(),sharp.getProgress()/100f);status.setText(rc==0?source.getWidth()+"×"+source.getHeight()+" → "+w+"×"+h+" · "+((System.nanoTime()-t)/1000000)+" ms":"Ошибка движка: "+rc);after.setImageBitmap(result);}
 private void save(){if(result==null){Toast.makeText(this,"Сначала выбери изображение",0).show();return;}Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/png");i.putExtra(Intent.EXTRA_TITLE,"NEON_upscaled.png");startActivityForResult(i,SAVE);}
}
